fragment SiteParts on Site {
  __typename
  title
  slug
  blocks {
    __typename
    ... on SiteBlocksHero {
      layout
      height
      backgroundType
      image
      videoUrl
      backgroundColor
      overlayColor
      overlayOpacity
      title
      subtitle
      primaryButton {
        __typename
        label
        url
      }
      secondaryButton {
        __typename
        label
        url
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksTextSection {
      layout
      title
      subtitle
      body
      images {
        __typename
        src
        alt
      }
      primaryButton {
        __typename
        label
        url
      }
      secondaryButton {
        __typename
        label
        url
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksInfoBoxes {
      title
      columns
      cards {
        __typename
        mediaType
        icon
        image
        title
        titleLink
        description
        button {
          __typename
          label
          url
        }
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksFeatureList {
      layout
      title
      intro
      items {
        __typename
        mediaType
        icon
        image
        title
        description
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksGallery {
      title
      displayMode
      columns
      autoplay
      navigation
      images {
        __typename
        src
        alt
        caption
        titleOverlay
        linkUrl
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksBigMedia {
      mediaType
      image
      videoUrl
      backgroundColor
      height
      heightPx
      overlayColor
      overlayOpacity
      title
      subtitle
      primaryButton {
        __typename
        label
        url
      }
      secondaryButton {
        __typename
        label
        url
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksTestimonials {
      layout
      title
      intro
      items {
        __typename
        quote
        authorName
        authorTitle
        authorPhoto
        companyLogo
        rating
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksSignupForm {
      title
      intro
      showNameField
      nameFieldLabel
      emailFieldLabel
      submitLabel
      submitColor
      submitStyle
      successAction
      successMessage
      redirectUrl
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksStats {
      layout
      columns
      title
      intro
      items {
        __typename
        number
        label
        mediaType
        icon
        image
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksHtmlEmbed {
      title
      intro
      width
      heightType
      heightPx
      html
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksContactForm {
      title
      intro
      showNameField
      nameRequired
      nameFieldLabel
      emailFieldLabel
      showSubjectField
      subjectRequired
      subjectFieldLabel
      subjectType
      subjectOptions {
        __typename
        option
      }
      messageFieldLabel
      submitLabel
      submitColor
      submitStyle
      successAction
      successMessage
      redirectUrl
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksExperiments {
      heading
      description
      experimentsList {
        __typename
        ... on SiteBlocksExperimentsExperimentsListExperimentRef {
          experimentId {
            ... on Experiment {
              __typename
              title
              matrixCode
              logo
              matrixPoints
              description
              link {
                ... on Site {
                  __typename
                  title
                  slug
                  blocks {
                    __typename
                    ... on SiteBlocksHero {
                      layout
                      height
                      backgroundType
                      image
                      videoUrl
                      backgroundColor
                      overlayColor
                      overlayOpacity
                      title
                      subtitle
                      primaryButton {
                        __typename
                        label
                        url
                      }
                      secondaryButton {
                        __typename
                        label
                        url
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksTextSection {
                      layout
                      title
                      subtitle
                      body
                      images {
                        __typename
                        src
                        alt
                      }
                      primaryButton {
                        __typename
                        label
                        url
                      }
                      secondaryButton {
                        __typename
                        label
                        url
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksInfoBoxes {
                      title
                      columns
                      cards {
                        __typename
                        mediaType
                        icon
                        image
                        title
                        titleLink
                        description
                        button {
                          __typename
                          label
                          url
                        }
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksFeatureList {
                      layout
                      title
                      intro
                      items {
                        __typename
                        mediaType
                        icon
                        image
                        title
                        description
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksGallery {
                      title
                      displayMode
                      columns
                      autoplay
                      navigation
                      images {
                        __typename
                        src
                        alt
                        caption
                        titleOverlay
                        linkUrl
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksBigMedia {
                      mediaType
                      image
                      videoUrl
                      backgroundColor
                      height
                      heightPx
                      overlayColor
                      overlayOpacity
                      title
                      subtitle
                      primaryButton {
                        __typename
                        label
                        url
                      }
                      secondaryButton {
                        __typename
                        label
                        url
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksTestimonials {
                      layout
                      title
                      intro
                      items {
                        __typename
                        quote
                        authorName
                        authorTitle
                        authorPhoto
                        companyLogo
                        rating
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksSignupForm {
                      title
                      intro
                      showNameField
                      nameFieldLabel
                      emailFieldLabel
                      submitLabel
                      submitColor
                      submitStyle
                      successAction
                      successMessage
                      redirectUrl
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksStats {
                      layout
                      columns
                      title
                      intro
                      items {
                        __typename
                        number
                        label
                        mediaType
                        icon
                        image
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksHtmlEmbed {
                      title
                      intro
                      width
                      heightType
                      heightPx
                      html
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksContactForm {
                      title
                      intro
                      showNameField
                      nameRequired
                      nameFieldLabel
                      emailFieldLabel
                      showSubjectField
                      subjectRequired
                      subjectFieldLabel
                      subjectType
                      subjectOptions {
                        __typename
                        option
                      }
                      messageFieldLabel
                      submitLabel
                      submitColor
                      submitStyle
                      successAction
                      successMessage
                      redirectUrl
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksExperiments {
                      heading
                      description
                      experimentsList {
                        __typename
                        ... on SiteBlocksExperimentsExperimentsListExperimentItem {
                          title
                          matrixCode
                          logo
                          matrixPoints
                          description
                        }
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                  }
                }
                ... on Document {
                  _sys {
                    filename
                    basename
                    hasReferences
                    breadcrumbs
                    path
                    relativePath
                    extension
                  }
                  id
                }
              }
            }
            ... on Document {
              _sys {
                filename
                basename
                hasReferences
                breadcrumbs
                path
                relativePath
                extension
              }
              id
            }
          }
        }
        ... on SiteBlocksExperimentsExperimentsListExperimentItem {
          title
          matrixCode
          logo
          matrixPoints
          description
          link {
            ... on Site {
              __typename
              title
              slug
              blocks {
                __typename
                ... on SiteBlocksHero {
                  layout
                  height
                  backgroundType
                  image
                  videoUrl
                  backgroundColor
                  overlayColor
                  overlayOpacity
                  title
                  subtitle
                  primaryButton {
                    __typename
                    label
                    url
                  }
                  secondaryButton {
                    __typename
                    label
                    url
                  }
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksTextSection {
                  layout
                  title
                  subtitle
                  body
                  images {
                    __typename
                    src
                    alt
                  }
                  primaryButton {
                    __typename
                    label
                    url
                  }
                  secondaryButton {
                    __typename
                    label
                    url
                  }
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksInfoBoxes {
                  title
                  columns
                  cards {
                    __typename
                    mediaType
                    icon
                    image
                    title
                    titleLink
                    description
                    button {
                      __typename
                      label
                      url
                    }
                  }
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksFeatureList {
                  layout
                  title
                  intro
                  items {
                    __typename
                    mediaType
                    icon
                    image
                    title
                    description
                  }
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksGallery {
                  title
                  displayMode
                  columns
                  autoplay
                  navigation
                  images {
                    __typename
                    src
                    alt
                    caption
                    titleOverlay
                    linkUrl
                  }
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksBigMedia {
                  mediaType
                  image
                  videoUrl
                  backgroundColor
                  height
                  heightPx
                  overlayColor
                  overlayOpacity
                  title
                  subtitle
                  primaryButton {
                    __typename
                    label
                    url
                  }
                  secondaryButton {
                    __typename
                    label
                    url
                  }
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksTestimonials {
                  layout
                  title
                  intro
                  items {
                    __typename
                    quote
                    authorName
                    authorTitle
                    authorPhoto
                    companyLogo
                    rating
                  }
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksSignupForm {
                  title
                  intro
                  showNameField
                  nameFieldLabel
                  emailFieldLabel
                  submitLabel
                  submitColor
                  submitStyle
                  successAction
                  successMessage
                  redirectUrl
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksStats {
                  layout
                  columns
                  title
                  intro
                  items {
                    __typename
                    number
                    label
                    mediaType
                    icon
                    image
                  }
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksHtmlEmbed {
                  title
                  intro
                  width
                  heightType
                  heightPx
                  html
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksContactForm {
                  title
                  intro
                  showNameField
                  nameRequired
                  nameFieldLabel
                  emailFieldLabel
                  showSubjectField
                  subjectRequired
                  subjectFieldLabel
                  subjectType
                  subjectOptions {
                    __typename
                    option
                  }
                  messageFieldLabel
                  submitLabel
                  submitColor
                  submitStyle
                  successAction
                  successMessage
                  redirectUrl
                  showInNav
                  navLabel
                  blockId
                }
                ... on SiteBlocksExperiments {
                  heading
                  description
                  experimentsList {
                    __typename
                    ... on SiteBlocksExperimentsExperimentsListExperimentRef {
                      experimentId {
                        ... on Experiment {
                          __typename
                          title
                          matrixCode
                          logo
                          matrixPoints
                          description
                        }
                        ... on Document {
                          _sys {
                            filename
                            basename
                            hasReferences
                            breadcrumbs
                            path
                            relativePath
                            extension
                          }
                          id
                        }
                      }
                    }
                    ... on SiteBlocksExperimentsExperimentsListExperimentItem {
                      title
                      matrixCode
                      logo
                      matrixPoints
                      description
                      link {
                        ... on Site {
                          __typename
                          title
                          slug
                          blocks {
                            __typename
                            ... on SiteBlocksHero {
                              layout
                              height
                              backgroundType
                              image
                              videoUrl
                              backgroundColor
                              overlayColor
                              overlayOpacity
                              title
                              subtitle
                              primaryButton {
                                __typename
                                label
                                url
                              }
                              secondaryButton {
                                __typename
                                label
                                url
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksTextSection {
                              layout
                              title
                              subtitle
                              body
                              images {
                                __typename
                                src
                                alt
                              }
                              primaryButton {
                                __typename
                                label
                                url
                              }
                              secondaryButton {
                                __typename
                                label
                                url
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksInfoBoxes {
                              title
                              columns
                              cards {
                                __typename
                                mediaType
                                icon
                                image
                                title
                                titleLink
                                description
                                button {
                                  __typename
                                  label
                                  url
                                }
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksFeatureList {
                              layout
                              title
                              intro
                              items {
                                __typename
                                mediaType
                                icon
                                image
                                title
                                description
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksGallery {
                              title
                              displayMode
                              columns
                              autoplay
                              navigation
                              images {
                                __typename
                                src
                                alt
                                caption
                                titleOverlay
                                linkUrl
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksBigMedia {
                              mediaType
                              image
                              videoUrl
                              backgroundColor
                              height
                              heightPx
                              overlayColor
                              overlayOpacity
                              title
                              subtitle
                              primaryButton {
                                __typename
                                label
                                url
                              }
                              secondaryButton {
                                __typename
                                label
                                url
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksTestimonials {
                              layout
                              title
                              intro
                              items {
                                __typename
                                quote
                                authorName
                                authorTitle
                                authorPhoto
                                companyLogo
                                rating
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksSignupForm {
                              title
                              intro
                              showNameField
                              nameFieldLabel
                              emailFieldLabel
                              submitLabel
                              submitColor
                              submitStyle
                              successAction
                              successMessage
                              redirectUrl
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksStats {
                              layout
                              columns
                              title
                              intro
                              items {
                                __typename
                                number
                                label
                                mediaType
                                icon
                                image
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksHtmlEmbed {
                              title
                              intro
                              width
                              heightType
                              heightPx
                              html
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksContactForm {
                              title
                              intro
                              showNameField
                              nameRequired
                              nameFieldLabel
                              emailFieldLabel
                              showSubjectField
                              subjectRequired
                              subjectFieldLabel
                              subjectType
                              subjectOptions {
                                __typename
                                option
                              }
                              messageFieldLabel
                              submitLabel
                              submitColor
                              submitStyle
                              successAction
                              successMessage
                              redirectUrl
                              showInNav
                              navLabel
                              blockId
                            }
                            ... on SiteBlocksExperiments {
                              heading
                              description
                              experimentsList {
                                __typename
                                ... on SiteBlocksExperimentsExperimentsListExperimentItem {
                                  title
                                  matrixCode
                                  logo
                                  matrixPoints
                                  description
                                }
                              }
                              showInNav
                              navLabel
                              blockId
                            }
                          }
                        }
                        ... on Document {
                          _sys {
                            filename
                            basename
                            hasReferences
                            breadcrumbs
                            path
                            relativePath
                            extension
                          }
                          id
                        }
                      }
                    }
                  }
                  showInNav
                  navLabel
                  blockId
                }
              }
            }
            ... on Document {
              _sys {
                filename
                basename
                hasReferences
                breadcrumbs
                path
                relativePath
                extension
              }
              id
            }
          }
        }
      }
      showInNav
      navLabel
      blockId
    }
  }
}

fragment HomepageParts on Homepage {
  __typename
  title
  subtitle
}

fragment TemplateParts on Template {
  __typename
  name
  description
}

fragment ExperimentParts on Experiment {
  __typename
  title
  matrixCode
  logo
  matrixPoints
  description
  link {
    ... on Site {
      __typename
      title
      slug
      blocks {
        __typename
        ... on SiteBlocksHero {
          layout
          height
          backgroundType
          image
          videoUrl
          backgroundColor
          overlayColor
          overlayOpacity
          title
          subtitle
          primaryButton {
            __typename
            label
            url
          }
          secondaryButton {
            __typename
            label
            url
          }
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksTextSection {
          layout
          title
          subtitle
          body
          images {
            __typename
            src
            alt
          }
          primaryButton {
            __typename
            label
            url
          }
          secondaryButton {
            __typename
            label
            url
          }
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksInfoBoxes {
          title
          columns
          cards {
            __typename
            mediaType
            icon
            image
            title
            titleLink
            description
            button {
              __typename
              label
              url
            }
          }
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksFeatureList {
          layout
          title
          intro
          items {
            __typename
            mediaType
            icon
            image
            title
            description
          }
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksGallery {
          title
          displayMode
          columns
          autoplay
          navigation
          images {
            __typename
            src
            alt
            caption
            titleOverlay
            linkUrl
          }
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksBigMedia {
          mediaType
          image
          videoUrl
          backgroundColor
          height
          heightPx
          overlayColor
          overlayOpacity
          title
          subtitle
          primaryButton {
            __typename
            label
            url
          }
          secondaryButton {
            __typename
            label
            url
          }
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksTestimonials {
          layout
          title
          intro
          items {
            __typename
            quote
            authorName
            authorTitle
            authorPhoto
            companyLogo
            rating
          }
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksSignupForm {
          title
          intro
          showNameField
          nameFieldLabel
          emailFieldLabel
          submitLabel
          submitColor
          submitStyle
          successAction
          successMessage
          redirectUrl
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksStats {
          layout
          columns
          title
          intro
          items {
            __typename
            number
            label
            mediaType
            icon
            image
          }
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksHtmlEmbed {
          title
          intro
          width
          heightType
          heightPx
          html
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksContactForm {
          title
          intro
          showNameField
          nameRequired
          nameFieldLabel
          emailFieldLabel
          showSubjectField
          subjectRequired
          subjectFieldLabel
          subjectType
          subjectOptions {
            __typename
            option
          }
          messageFieldLabel
          submitLabel
          submitColor
          submitStyle
          successAction
          successMessage
          redirectUrl
          showInNav
          navLabel
          blockId
        }
        ... on SiteBlocksExperiments {
          heading
          description
          experimentsList {
            __typename
            ... on SiteBlocksExperimentsExperimentsListExperimentRef {
              experimentId {
                ... on Experiment {
                  __typename
                  title
                  matrixCode
                  logo
                  matrixPoints
                  description
                }
                ... on Document {
                  _sys {
                    filename
                    basename
                    hasReferences
                    breadcrumbs
                    path
                    relativePath
                    extension
                  }
                  id
                }
              }
            }
            ... on SiteBlocksExperimentsExperimentsListExperimentItem {
              title
              matrixCode
              logo
              matrixPoints
              description
              link {
                ... on Site {
                  __typename
                  title
                  slug
                  blocks {
                    __typename
                    ... on SiteBlocksHero {
                      layout
                      height
                      backgroundType
                      image
                      videoUrl
                      backgroundColor
                      overlayColor
                      overlayOpacity
                      title
                      subtitle
                      primaryButton {
                        __typename
                        label
                        url
                      }
                      secondaryButton {
                        __typename
                        label
                        url
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksTextSection {
                      layout
                      title
                      subtitle
                      body
                      images {
                        __typename
                        src
                        alt
                      }
                      primaryButton {
                        __typename
                        label
                        url
                      }
                      secondaryButton {
                        __typename
                        label
                        url
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksInfoBoxes {
                      title
                      columns
                      cards {
                        __typename
                        mediaType
                        icon
                        image
                        title
                        titleLink
                        description
                        button {
                          __typename
                          label
                          url
                        }
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksFeatureList {
                      layout
                      title
                      intro
                      items {
                        __typename
                        mediaType
                        icon
                        image
                        title
                        description
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksGallery {
                      title
                      displayMode
                      columns
                      autoplay
                      navigation
                      images {
                        __typename
                        src
                        alt
                        caption
                        titleOverlay
                        linkUrl
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksBigMedia {
                      mediaType
                      image
                      videoUrl
                      backgroundColor
                      height
                      heightPx
                      overlayColor
                      overlayOpacity
                      title
                      subtitle
                      primaryButton {
                        __typename
                        label
                        url
                      }
                      secondaryButton {
                        __typename
                        label
                        url
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksTestimonials {
                      layout
                      title
                      intro
                      items {
                        __typename
                        quote
                        authorName
                        authorTitle
                        authorPhoto
                        companyLogo
                        rating
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksSignupForm {
                      title
                      intro
                      showNameField
                      nameFieldLabel
                      emailFieldLabel
                      submitLabel
                      submitColor
                      submitStyle
                      successAction
                      successMessage
                      redirectUrl
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksStats {
                      layout
                      columns
                      title
                      intro
                      items {
                        __typename
                        number
                        label
                        mediaType
                        icon
                        image
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksHtmlEmbed {
                      title
                      intro
                      width
                      heightType
                      heightPx
                      html
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksContactForm {
                      title
                      intro
                      showNameField
                      nameRequired
                      nameFieldLabel
                      emailFieldLabel
                      showSubjectField
                      subjectRequired
                      subjectFieldLabel
                      subjectType
                      subjectOptions {
                        __typename
                        option
                      }
                      messageFieldLabel
                      submitLabel
                      submitColor
                      submitStyle
                      successAction
                      successMessage
                      redirectUrl
                      showInNav
                      navLabel
                      blockId
                    }
                    ... on SiteBlocksExperiments {
                      heading
                      description
                      experimentsList {
                        __typename
                        ... on SiteBlocksExperimentsExperimentsListExperimentItem {
                          title
                          matrixCode
                          logo
                          matrixPoints
                          description
                        }
                      }
                      showInNav
                      navLabel
                      blockId
                    }
                  }
                }
                ... on Document {
                  _sys {
                    filename
                    basename
                    hasReferences
                    breadcrumbs
                    path
                    relativePath
                    extension
                  }
                  id
                }
              }
            }
          }
          showInNav
          navLabel
          blockId
        }
      }
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
}
