//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  template: Template;
  templateConnection: TemplateConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryTemplateArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTemplateConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TemplateFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  template?: InputMaybe<TemplateFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Homepage | Template | Folder;

export type SiteBlocksHero = {
  __typename?: 'SiteBlocksHero';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  showInNav?: Maybe<Scalars['Boolean']['output']>;
  navLabel?: Maybe<Scalars['String']['output']>;
  blockId?: Maybe<Scalars['String']['output']>;
};

export type SiteBlocksTextSection = {
  __typename?: 'SiteBlocksTextSection';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  showInNav?: Maybe<Scalars['Boolean']['output']>;
  navLabel?: Maybe<Scalars['String']['output']>;
  blockId?: Maybe<Scalars['String']['output']>;
};

export type SiteBlocksGalleryImages = {
  __typename?: 'SiteBlocksGalleryImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type SiteBlocksGallery = {
  __typename?: 'SiteBlocksGallery';
  title?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<SiteBlocksGalleryImages>>>;
  showInNav?: Maybe<Scalars['Boolean']['output']>;
  navLabel?: Maybe<Scalars['String']['output']>;
  blockId?: Maybe<Scalars['String']['output']>;
};

export type SiteBlocksBigMedia = {
  __typename?: 'SiteBlocksBigMedia';
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  layout?: Maybe<Scalars['String']['output']>;
  showInNav?: Maybe<Scalars['Boolean']['output']>;
  navLabel?: Maybe<Scalars['String']['output']>;
  blockId?: Maybe<Scalars['String']['output']>;
};

export type SiteBlocksFullWidthImage = {
  __typename?: 'SiteBlocksFullWidthImage';
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  showInNav?: Maybe<Scalars['Boolean']['output']>;
  navLabel?: Maybe<Scalars['String']['output']>;
  blockId?: Maybe<Scalars['String']['output']>;
};

export type SiteBlocksVideoBlock = {
  __typename?: 'SiteBlocksVideoBlock';
  title?: Maybe<Scalars['String']['output']>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  showInNav?: Maybe<Scalars['Boolean']['output']>;
  navLabel?: Maybe<Scalars['String']['output']>;
  blockId?: Maybe<Scalars['String']['output']>;
};

export type SiteBlocks = SiteBlocksHero | SiteBlocksTextSection | SiteBlocksGallery | SiteBlocksBigMedia | SiteBlocksFullWidthImage | SiteBlocksVideoBlock;

export type Site = Node & Document & {
  __typename?: 'Site';
  title: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  blocks?: Maybe<Array<Maybe<SiteBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SiteBlocksHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  showInNav?: InputMaybe<BooleanFilter>;
  navLabel?: InputMaybe<StringFilter>;
  blockId?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SiteBlocksTextSectionFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  showInNav?: InputMaybe<BooleanFilter>;
  navLabel?: InputMaybe<StringFilter>;
  blockId?: InputMaybe<StringFilter>;
};

export type SiteBlocksGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type SiteBlocksGalleryFilter = {
  title?: InputMaybe<StringFilter>;
  images?: InputMaybe<SiteBlocksGalleryImagesFilter>;
  showInNav?: InputMaybe<BooleanFilter>;
  navLabel?: InputMaybe<StringFilter>;
  blockId?: InputMaybe<StringFilter>;
};

export type SiteBlocksBigMediaFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  layout?: InputMaybe<StringFilter>;
  showInNav?: InputMaybe<BooleanFilter>;
  navLabel?: InputMaybe<StringFilter>;
  blockId?: InputMaybe<StringFilter>;
};

export type SiteBlocksFullWidthImageFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  showInNav?: InputMaybe<BooleanFilter>;
  navLabel?: InputMaybe<StringFilter>;
  blockId?: InputMaybe<StringFilter>;
};

export type SiteBlocksVideoBlockFilter = {
  title?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  showInNav?: InputMaybe<BooleanFilter>;
  navLabel?: InputMaybe<StringFilter>;
  blockId?: InputMaybe<StringFilter>;
};

export type SiteBlocksFilter = {
  hero?: InputMaybe<SiteBlocksHeroFilter>;
  textSection?: InputMaybe<SiteBlocksTextSectionFilter>;
  gallery?: InputMaybe<SiteBlocksGalleryFilter>;
  bigMedia?: InputMaybe<SiteBlocksBigMediaFilter>;
  fullWidthImage?: InputMaybe<SiteBlocksFullWidthImageFilter>;
  videoBlock?: InputMaybe<SiteBlocksVideoBlockFilter>;
};

export type SiteFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<SiteBlocksFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Template = Node & Document & {
  __typename?: 'Template';
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TemplateFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type TemplateConnectionEdges = {
  __typename?: 'TemplateConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Template>;
};

export type TemplateConnection = Connection & {
  __typename?: 'TemplateConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TemplateConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateTemplate: Template;
  createTemplate: Template;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateTemplateArgs = {
  relativePath: Scalars['String']['input'];
  params: TemplateMutation;
};


export type MutationCreateTemplateArgs = {
  relativePath: Scalars['String']['input'];
  params: TemplateMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  template?: InputMaybe<TemplateMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  template?: InputMaybe<TemplateMutation>;
};

export type SiteBlocksHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  showInNav?: InputMaybe<Scalars['Boolean']['input']>;
  navLabel?: InputMaybe<Scalars['String']['input']>;
  blockId?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBlocksTextSectionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  showInNav?: InputMaybe<Scalars['Boolean']['input']>;
  navLabel?: InputMaybe<Scalars['String']['input']>;
  blockId?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBlocksGalleryImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBlocksGalleryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<SiteBlocksGalleryImagesMutation>>>;
  showInNav?: InputMaybe<Scalars['Boolean']['input']>;
  navLabel?: InputMaybe<Scalars['String']['input']>;
  blockId?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBlocksBigMediaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  layout?: InputMaybe<Scalars['String']['input']>;
  showInNav?: InputMaybe<Scalars['Boolean']['input']>;
  navLabel?: InputMaybe<Scalars['String']['input']>;
  blockId?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBlocksFullWidthImageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  showInNav?: InputMaybe<Scalars['Boolean']['input']>;
  navLabel?: InputMaybe<Scalars['String']['input']>;
  blockId?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBlocksVideoBlockMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  showInNav?: InputMaybe<Scalars['Boolean']['input']>;
  navLabel?: InputMaybe<Scalars['String']['input']>;
  blockId?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBlocksMutation = {
  hero?: InputMaybe<SiteBlocksHeroMutation>;
  textSection?: InputMaybe<SiteBlocksTextSectionMutation>;
  gallery?: InputMaybe<SiteBlocksGalleryMutation>;
  bigMedia?: InputMaybe<SiteBlocksBigMediaMutation>;
  fullWidthImage?: InputMaybe<SiteBlocksFullWidthImageMutation>;
  videoBlock?: InputMaybe<SiteBlocksVideoBlockMutation>;
};

export type SiteMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<SiteBlocksMutation>>>;
};

export type HomepageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type TemplateMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SitePartsFragment = { __typename: 'Site', title: string, slug?: string | null, blocks?: Array<{ __typename: 'SiteBlocksHero', title?: string | null, subtitle?: string | null, image?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksTextSection', title?: string | null, body?: any | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksGallery', title?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null, images?: Array<{ __typename: 'SiteBlocksGalleryImages', src?: string | null, alt?: string | null } | null> | null } | { __typename: 'SiteBlocksBigMedia', title?: string | null, image?: string | null, layout?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksFullWidthImage', title?: string | null, image?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksVideoBlock', title?: string | null, videoUrl?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | null> | null };

export type HomepagePartsFragment = { __typename: 'Homepage', title?: string | null, subtitle?: string | null };

export type TemplatePartsFragment = { __typename: 'Template', name: string, description?: string | null };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, title: string, slug?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'SiteBlocksHero', title?: string | null, subtitle?: string | null, image?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksTextSection', title?: string | null, body?: any | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksGallery', title?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null, images?: Array<{ __typename: 'SiteBlocksGalleryImages', src?: string | null, alt?: string | null } | null> | null } | { __typename: 'SiteBlocksBigMedia', title?: string | null, image?: string | null, layout?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksFullWidthImage', title?: string | null, image?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksVideoBlock', title?: string | null, videoUrl?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | null> | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, title: string, slug?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'SiteBlocksHero', title?: string | null, subtitle?: string | null, image?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksTextSection', title?: string | null, body?: any | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksGallery', title?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null, images?: Array<{ __typename: 'SiteBlocksGalleryImages', src?: string | null, alt?: string | null } | null> | null } | { __typename: 'SiteBlocksBigMedia', title?: string | null, image?: string | null, layout?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksFullWidthImage', title?: string | null, image?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | { __typename: 'SiteBlocksVideoBlock', title?: string | null, videoUrl?: string | null, showInNav?: boolean | null, navLabel?: string | null, blockId?: string | null } | null> | null } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, title?: string | null, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, title?: string | null, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TemplateQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TemplateQuery = { __typename?: 'Query', template: { __typename: 'Template', id: string, name: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TemplateConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TemplateFilter>;
}>;


export type TemplateConnectionQuery = { __typename?: 'Query', templateConnection: { __typename?: 'TemplateConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TemplateConnectionEdges', cursor: string, node?: { __typename: 'Template', id: string, name: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  title
  slug
  blocks {
    __typename
    ... on SiteBlocksHero {
      title
      subtitle
      image
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksTextSection {
      title
      body
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksGallery {
      title
      images {
        __typename
        src
        alt
      }
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksBigMedia {
      title
      image
      layout
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksFullWidthImage {
      title
      image
      showInNav
      navLabel
      blockId
    }
    ... on SiteBlocksVideoBlock {
      title
      videoUrl
      showInNav
      navLabel
      blockId
    }
  }
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  title
  subtitle
}
    `;
export const TemplatePartsFragmentDoc = gql`
    fragment TemplateParts on Template {
  __typename
  name
  description
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const TemplateDocument = gql`
    query template($relativePath: String!) {
  template(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TemplateParts
  }
}
    ${TemplatePartsFragmentDoc}`;
export const TemplateConnectionDocument = gql`
    query templateConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TemplateFilter) {
  templateConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TemplateParts
      }
    }
  }
}
    ${TemplatePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    template(variables: TemplateQueryVariables, options?: C): Promise<{data: TemplateQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TemplateQueryVariables, query: string}> {
        return requester<{data: TemplateQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TemplateQueryVariables, query: string}, TemplateQueryVariables>(TemplateDocument, variables, options);
      },
    templateConnection(variables?: TemplateConnectionQueryVariables, options?: C): Promise<{data: TemplateConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TemplateConnectionQueryVariables, query: string}> {
        return requester<{data: TemplateConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TemplateConnectionQueryVariables, query: string}, TemplateConnectionQueryVariables>(TemplateConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  